"use strict";
let vengador = 123;
let existe;
let derrotas;
vengador = "Dr. Strange";
console.log(vengador.charAt(0));
vengador = 123.4545;
console.log(vengador.toFixed(2));
vengador = true;
console.log(vengador);
console.log(existe);
console.log(derrotas);
